sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm test -- --coverage

after_success:
  - docker build -t st3f4n/multi-client ./client
  - docker build -t st3f4n/multi-nginx ./nginx
  - docker build -t st3f4n/multi-server ./server
  - docker build -t st3f4n/multi-worker ./worker
  #log in to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to the hub
  - docker push st3f4n/multi-client
  - docker push st3f4n/multi-nginx
  - docker push st3f4n/multi-server
  - docker push st3f4n/multi-worker
